modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Stronger-Snowballs/issues"
license="LGPL v2.1"

[[mods]]
modId="strongersnowballs"
updateJSONURL="https://updates.blamejared.com/get?n=strongersnowballs&gv=1.16.3"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.strongersnowballs]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.strongersnowballs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="SERVER"