modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Stronger-Snowballs/issues"
license="LGPL v2.1"

[[mods]]
modId="strongersnowballs"
updateJSONURL="https://updates.blamejared.com/get?n=strongersnowballs&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''